// =============================== WARNING ===============================
// This file defines the internal grpc API for the Edge service.
// Follow all Protobuf best practices outlined in shared.proto.
// =======================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: edge/v1/edge.proto

package edgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMProviderModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMProviderModel) Reset() {
	*x = LLMProviderModel{}
	mi := &file_edge_v1_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMProviderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMProviderModel) ProtoMessage() {}

func (x *LLMProviderModel) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMProviderModel.ProtoReflect.Descriptor instead.
func (*LLMProviderModel) Descriptor() ([]byte, []int) {
	return file_edge_v1_edge_proto_rawDescGZIP(), []int{0}
}

func (x *LLMProviderModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMProviderModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMProviderModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LLMProviderModel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type TTSProviderModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSProviderModel) Reset() {
	*x = TTSProviderModel{}
	mi := &file_edge_v1_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSProviderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSProviderModel) ProtoMessage() {}

func (x *TTSProviderModel) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSProviderModel.ProtoReflect.Descriptor instead.
func (*TTSProviderModel) Descriptor() ([]byte, []int) {
	return file_edge_v1_edge_proto_rawDescGZIP(), []int{1}
}

func (x *TTSProviderModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TTSProviderModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TTSProviderModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TTSProviderModel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type STTProviderModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STTProviderModel) Reset() {
	*x = STTProviderModel{}
	mi := &file_edge_v1_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STTProviderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STTProviderModel) ProtoMessage() {}

func (x *STTProviderModel) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STTProviderModel.ProtoReflect.Descriptor instead.
func (*STTProviderModel) Descriptor() ([]byte, []int) {
	return file_edge_v1_edge_proto_rawDescGZIP(), []int{2}
}

func (x *STTProviderModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *STTProviderModel) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *STTProviderModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *STTProviderModel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ListProviderModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderModelsRequest) Reset() {
	*x = ListProviderModelsRequest{}
	mi := &file_edge_v1_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderModelsRequest) ProtoMessage() {}

func (x *ListProviderModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderModelsRequest.ProtoReflect.Descriptor instead.
func (*ListProviderModelsRequest) Descriptor() ([]byte, []int) {
	return file_edge_v1_edge_proto_rawDescGZIP(), []int{3}
}

type ListProviderModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Llm           []*LLMProviderModel    `protobuf:"bytes,1,rep,name=llm,proto3" json:"llm,omitempty"`
	Tts           []*TTSProviderModel    `protobuf:"bytes,2,rep,name=tts,proto3" json:"tts,omitempty"`
	Stt           []*STTProviderModel    `protobuf:"bytes,3,rep,name=stt,proto3" json:"stt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderModelsResponse) Reset() {
	*x = ListProviderModelsResponse{}
	mi := &file_edge_v1_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderModelsResponse) ProtoMessage() {}

func (x *ListProviderModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edge_v1_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderModelsResponse.ProtoReflect.Descriptor instead.
func (*ListProviderModelsResponse) Descriptor() ([]byte, []int) {
	return file_edge_v1_edge_proto_rawDescGZIP(), []int{4}
}

func (x *ListProviderModelsResponse) GetLlm() []*LLMProviderModel {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *ListProviderModelsResponse) GetTts() []*TTSProviderModel {
	if x != nil {
		return x.Tts
	}
	return nil
}

func (x *ListProviderModelsResponse) GetStt() []*STTProviderModel {
	if x != nil {
		return x.Stt
	}
	return nil
}

var File_edge_v1_edge_proto protoreflect.FileDescriptor

const file_edge_v1_edge_proto_rawDesc = "" +
	"\n" +
	"\x12edge/v1/edge.proto\x12\rsaasy.edge.v1\"|\n" +
	"\x10LLMProviderModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"|\n" +
	"\x10TTSProviderModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"|\n" +
	"\x10STTProviderModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"\x1b\n" +
	"\x19ListProviderModelsRequest\"\xb5\x01\n" +
	"\x1aListProviderModelsResponse\x121\n" +
	"\x03llm\x18\x01 \x03(\v2\x1f.saasy.edge.v1.LLMProviderModelR\x03llm\x121\n" +
	"\x03tts\x18\x02 \x03(\v2\x1f.saasy.edge.v1.TTSProviderModelR\x03tts\x121\n" +
	"\x03stt\x18\x03 \x03(\v2\x1f.saasy.edge.v1.STTProviderModelR\x03stt2x\n" +
	"\vEdgeService\x12i\n" +
	"\x12ListProviderModels\x12(.saasy.edge.v1.ListProviderModelsRequest\x1a).saasy.edge.v1.ListProviderModelsResponseB7Z5github.com/saasybyte/saasy-edge/pkg/pb/edge/v1;edgev1b\x06proto3"

var (
	file_edge_v1_edge_proto_rawDescOnce sync.Once
	file_edge_v1_edge_proto_rawDescData []byte
)

func file_edge_v1_edge_proto_rawDescGZIP() []byte {
	file_edge_v1_edge_proto_rawDescOnce.Do(func() {
		file_edge_v1_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_v1_edge_proto_rawDesc), len(file_edge_v1_edge_proto_rawDesc)))
	})
	return file_edge_v1_edge_proto_rawDescData
}

var file_edge_v1_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_edge_v1_edge_proto_goTypes = []any{
	(*LLMProviderModel)(nil),           // 0: saasy.edge.v1.LLMProviderModel
	(*TTSProviderModel)(nil),           // 1: saasy.edge.v1.TTSProviderModel
	(*STTProviderModel)(nil),           // 2: saasy.edge.v1.STTProviderModel
	(*ListProviderModelsRequest)(nil),  // 3: saasy.edge.v1.ListProviderModelsRequest
	(*ListProviderModelsResponse)(nil), // 4: saasy.edge.v1.ListProviderModelsResponse
}
var file_edge_v1_edge_proto_depIdxs = []int32{
	0, // 0: saasy.edge.v1.ListProviderModelsResponse.llm:type_name -> saasy.edge.v1.LLMProviderModel
	1, // 1: saasy.edge.v1.ListProviderModelsResponse.tts:type_name -> saasy.edge.v1.TTSProviderModel
	2, // 2: saasy.edge.v1.ListProviderModelsResponse.stt:type_name -> saasy.edge.v1.STTProviderModel
	3, // 3: saasy.edge.v1.EdgeService.ListProviderModels:input_type -> saasy.edge.v1.ListProviderModelsRequest
	4, // 4: saasy.edge.v1.EdgeService.ListProviderModels:output_type -> saasy.edge.v1.ListProviderModelsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_edge_v1_edge_proto_init() }
func file_edge_v1_edge_proto_init() {
	if File_edge_v1_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_v1_edge_proto_rawDesc), len(file_edge_v1_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edge_v1_edge_proto_goTypes,
		DependencyIndexes: file_edge_v1_edge_proto_depIdxs,
		MessageInfos:      file_edge_v1_edge_proto_msgTypes,
	}.Build()
	File_edge_v1_edge_proto = out.File
	file_edge_v1_edge_proto_goTypes = nil
	file_edge_v1_edge_proto_depIdxs = nil
}
