// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// LLMProviderModel defines model for LLMProviderModel.
type LLMProviderModel struct {
	DisplayName string             `json:"displayName"`
	Id          openapi_types.UUID `json:"id"`
	ModelId     string             `json:"modelId"`
	Provider    string             `json:"provider"`
}

// ProviderModelsResponse defines model for ProviderModelsResponse.
type ProviderModelsResponse struct {
	Llm []LLMProviderModel `json:"llm"`
	Stt []STTProviderModel `json:"stt"`
	Tts []TTSProviderModel `json:"tts"`
}

// STTProviderModel defines model for STTProviderModel.
type STTProviderModel struct {
	DisplayName string             `json:"displayName"`
	Id          openapi_types.UUID `json:"id"`
	ModelId     string             `json:"modelId"`
	Provider    string             `json:"provider"`
}

// TTSProviderModel defines model for TTSProviderModel.
type TTSProviderModel struct {
	DisplayName string             `json:"displayName"`
	Id          openapi_types.UUID `json:"id"`
	ModelId     string             `json:"modelId"`
	Provider    string             `json:"provider"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all provider models
	// (GET /provider-models)
	ListProviderModels(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListProviderModels operation middleware
func (siw *ServerInterfaceWrapper) ListProviderModels(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProviderModels(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/provider-models", wrapper.ListProviderModels)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yUP2/bMBDFv4pw7ahaSrNx69AhaNIGtbfAAyuenQv4r+TJgGDouxdH2Q4cuXDmTBT/",
	"6N17P+m4hy64GDx6zqD2kLtndLo83t8/PKawI4PpIRi0shZTiJiYsJwwlKPVw0/tUKY8RAQFmRP5LYw1",
	"kJHlTUhOMyjoezJQz485Ub8zFyXiwcGFzbGGhH97SmhAPUHRPh1/Va3PbK5P9cOfF+xYapylzL8xx+Az",
	"zuNa62QgRlfmnxNuQMGn5hVhc+DXzOCNp8I6JT3IPDO/W2+5Wl3V4+kTvktvtVpe0XuDV8JPJSbjl0DO",
	"TH7UP2ZG72MGFR3ym1AqEFvZW2qdh+q72WL17fEOathhyhQ8KLhZtItWnIWIXkcCBbeLdnErxTU/Fy7N",
	"0caXYqKsbbH0geDTTMFLXrinzOeNCRJq6s3y2te2laELntEXBR2jpa5oNC9ZPB0vtGvt8J8roBAwmLtE",
	"kaeQv34UvLl3TqfhYLTS1lbHZJU72mW9zcL/beZ10c2YhB2opz30yYKCRkdqdjcwrsd/AQAA//9ShNeo",
	"mAUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
