// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LlmProviderModel struct {
	ID          pgtype.UUID        `json:"id"`
	Provider    string             `json:"provider"`
	ModelID     string             `json:"modelId"`
	DisplayName string             `json:"displayName"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}

type SttProviderModel struct {
	ID          pgtype.UUID        `json:"id"`
	Provider    string             `json:"provider"`
	ModelID     string             `json:"modelId"`
	DisplayName string             `json:"displayName"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}

type TtsProviderModel struct {
	ID          pgtype.UUID        `json:"id"`
	Provider    string             `json:"provider"`
	ModelID     string             `json:"modelId"`
	DisplayName string             `json:"displayName"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	DeletedAt   pgtype.Timestamptz `json:"deletedAt"`
}
