// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stt_provider_models.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSTTProviderModels = `-- name: ListSTTProviderModels :many
SELECT id, provider, model_id, display_name
FROM stt_provider_models
WHERE deleted_at IS NULL
`

type ListSTTProviderModelsRow struct {
	ID          pgtype.UUID `json:"id"`
	Provider    string      `json:"provider"`
	ModelID     string      `json:"modelId"`
	DisplayName string      `json:"displayName"`
}

func (q *Queries) ListSTTProviderModels(ctx context.Context) ([]ListSTTProviderModelsRow, error) {
	rows, err := q.db.Query(ctx, listSTTProviderModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSTTProviderModelsRow
	for rows.Next() {
		var i ListSTTProviderModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
